# Generated by Django 5.2.3 on 2025-11-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
